import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import SideMenu from '@/components/custom/side-menu';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className=''>
      <body className={inter.className}>
        <div className='border-b'>
          <div className='flex h-16 items-center px-4 container mx-auto'>
            <span className='ml-4'>PHOTOS APP</span>
            <div className='ml-auto flex items-center space-x-4'>
              <Avatar>
                <AvatarImage src='https://github.com/shadcn.png' />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>
            </div>
          </div>
        </div>
        <div className='flex container px-4  mx-auto'>
          <SideMenu />
          <div className='w-full pt-5'>{children}</div>
        </div>
      </body>
    </html>
  );
}
